# Generated by Django 2.2 on 2019-04-30 15:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0008_attachment_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='example_context',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Context'),
        ),
    ]
