# Generated by Django 2.2 on 2019-05-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0009_emailtemplate_example_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
    ]
